# Generated by Django 2.2.2 on 2019-06-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signuppage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='username',
        ),
    ]
