# Generated by Django 2.2.2 on 2019-06-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signuppage', '0002_remove_users_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
