# Generated by Django 2.2.2 on 2019-06-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signuppage', '0003_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='full_name',
            field=models.CharField(default='fulln', max_length=200),
        ),
    ]
