# Generated by Django 2.2.2 on 2019-06-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signuppage', '0004_auto_20190628_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(default='em', max_length=200),
        ),
        migrations.AlterField(
            model_name='users',
            name='password',
            field=models.CharField(default='1234', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone_number',
            field=models.CharField(default='120732', max_length=10),
        ),
    ]
