# Generated by Django 2.2.2 on 2019-06-28 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signuppage', '0005_auto_20190628_2228'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='full_name',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
